services:
  - type: web
    name: raid-ai-chat
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AI_PROVIDER
        value: huggingface
      - key: AI_API_KEY
        sync: false
      - key: API_URL
        sync: false